### PR TITLE
Add "Oasis Trade Digital Asset Assessment Framework" PDF

### PR DESCRIPTION
**Pull request by ferni**

### CODE REVIEW

**Comment by levity** [comment]
@ferni What is this for?

**Comment by ferni** [comment]
It's a doc that the legal team said that should be there that I had forgotten to add at first.  I hope it's cool that I didn't ask for review.

**Comment by levity** [comment]
It doesn't feel right to me to use this repo for hosting PDFs. Better to store the actual file somewhere else and just link to it from the site.

**Comment by ferni** [comment]
Ok yeah, you're probably right. I'll make a new PR reverting this one.

**Pull request merged**
