### PR TITLE
Feature/update mcd plugin

### PR DESCRIPTION
**Pull request by shkfnly**
Update the MCD portal to use the more robust dai.js/mcd-plugin updates

### CODE REVIEW

**Comment by shkfnly** [comment]
@adrianleb any thoughts on why this build is failing?

**Comment by levity** [comment]
@shkfnly note that Travis is erroring with:
```
error Couldn't find any versions for "@makerdao/dai" that matches "0.15.2-kovan.2"
```

**Comment by shkfnly** [comment]
I made the requested changes, I realized I don't have permission to publish the new package, so I'm not able to yarn to update the yarn.lock which means the build is no updated I believe.

I'm also interested in the ways we are publishing plugins vs the main dai.js library, and when they should be respectively updated.

**Comment by adrianleb** [comment]
Latest SDK changes were part of `dai-plugin-mcd` which wasn't published before this PR was merged, we ended up with a broken dev env.

@shkfnly you should now be able to publish package versions.

For now this has been resolved, dai-plugin-mcd 0.1.5 was published and the mcd cdp portal code updated to reflect that.

Let's make sure code works **with npm link disabled** before merging PRs in the future!

**Pull request merged**
