### PR TITLE
work with local testchain snapshot

### PR DESCRIPTION
**Pull request by levity**
This is the set of changes I've had to make so far to get the portal working with the local testchain. 

## starting the local testchain

```
cd $DAIJS # your dai.js path
git checkout dev
git pull
git submodule update --init --recursive
yarn test:net -s mcd-step-4 --fast
```

## if you also want to make changes to dai.js / dai-plugin-mcd

Here's how you would get things running and auto-refreshing when you make changes to either dai.js or the MCD plugin:

one-time prep:
```
npm i -g sane yalc
```

terminal 2:
```
cd $DAIJS
sane "yarn build:backend && cd dist && yalc publish && cd $PORTAL && yalc link @makerdao/dai" src --wait=3
```

terminal 3:
```
cd $DAIJS/lib/dai-plugin-mcd
sane "yalc publish && cd $PORTAL && yalc link @makerdao/dai-plugin-mcd" src --wait=3
```

terminal 4:
```
cd $PORTAL # your mcd portal path
yarn start
```

### CODE REVIEW

**Comment by levity** [comment]
Haven't done much testing yet, so there's probably more to do to get it working all the way through. And the issue with price feeds being Median on Kovan and DSValue in the snapshots is a pain; the workaround I put in place is obviously a hack.

**Comment by levity** [comment]
TODO

- [ ] remove redundant testchain addresses (rely on plugin)
- [ ] come up with a better way to toggle between Median and DSValue

**Comment by levity** [comment]
OK, this is ready for review!

It is set up by default to handle an environment with Median price feeds. To handle an environment with DSValue price feeds, add `simplePriceFeeds=1` to the URL query params.

To test this against a local testchain, please run the commands described in the "terminal 1" section above to start the testchain, and then fire up the MCD portal with `?network=test&simplePriceFeeds=1`.

**Comment by jparklev** [comment]
was able to open a cdp on the local chain using MM with [one of these keys](https://github.com/makerdao/dai.js/blob/dev/test/helpers/testAccounts.json) imported. made [this PR](https://github.com/makerdao/dai.js/pull/100). i think we still need [added tokens](https://github.com/makerdao/dai.js/blob/ebac2beb909aefa74d35a5d68719549ff79449ee/lib/dai-plugin-mcd/src/index.js#L101) to accept a string `data.address` so that we can use override addresses for tokens, too.

**Comment by adrianleb** [comment]
My first thought was - why am I looking at npm linking instructions if all I want is to run a testchain instance and this being a PR about local testchain?

These were the steps I took to get things running after reading your comments:
- Make sure `seth` is installed
 - ```
    git clone @makerdao/dai.js
    cd dai.js && yarn && git submodule update --init --recursive
    yarn test:net -s mcd-step-4 --fast
   ```

- Add `localhost:2000` as a custon network to Metamask

- Run `mcd-cdp-portal` as usual
- Navigate to `http://localhost:3000?network=test&simplePriceFeeds=1`

I'm still not able to develop on mcd-cdp-portal, where can one find a wallet with seeded balances?

Def. think it's useful having instructions on how to run all things all the time, but truth is the 80% use case is just developing the frontend using published versions of said sdk libs. it makes less and less sense having `testchain` be a `dai.js` submodule if one is not actively working on the sdk.

That aside, I think this is a great step for the developer experience around this project 🙏.

**Comment by b-pmcg** [comment]
I was able to get it up and running, but I had to make some adjustments to handle added contracts with no network properties.

**Comment by b-pmcg** [comment]
> 
> I'm still not able to develop on mcd-cdp-portal, where can one find a wallet with seeded balances?

@adrianleb using the mnemonic that's built into the deploy script outputs `"ETH_FROM": "0x16fb96a5fa0427af0c8f7cf1eb4870231c8154b6"`  to `testchain/lib/out/addresses.json`. The private key for that (`474beb999fed1b3af2ea048f963833c686a0fba05f5724cb6417cf3b8ee9697e`) can be found in `test/helpers/testAccounts.json' and you can send yourself ETH/COL1, etc.

We should probably add this to the testchain setup documentation.

**Comment by levity** [comment]
> > I'm still not able to develop on mcd-cdp-portal, where can one find a wallet with seeded balances?
> 
> @adrianleb using the mnemonic that's built into the deploy script outputs `"ETH_FROM": "0x16fb96a5fa0427af0c8f7cf1eb4870231c8154b6"` to `testchain/lib/out/addresses.json`. The private key for that (`474beb999fed1b3af2ea048f963833c686a0fba05f5724cb6417cf3b8ee9697e`) can be found in `test/helpers/testAccounts.json' and you can send yourself ETH/COL1, etc.
> 
> We should probably add this to the testchain setup documentation.

oh yeah, we should just bundle a script that makes it easy to send ETH/COLn from the creator address to the user's metamask account

**Comment by levity** [comment]
> My first thought was - why am I looking at npm linking instructions if all I want is to run a testchain instance and this being a PR about local testchain?

@adrianleb my bad, i should have edited that out. as you've noticed, the dai and dai-plugin-mcd deps were updated so you don't need `yalc link` to use this.

**Comment by levity** [comment]
> it makes less and less sense having testchain be a dai.js submodule if one is not actively working on the sdk.

You can actually do all this with a standalone copy of https://github.com/makerdao/testchain; just substitute `scripts/launch` for `yarn test:net`. i just provided instructions based on dai.js because everyone has a copy already.

**Comment by levity** [comment]
@jparklev did you mean to put "QOL tweaks" on develop?

**Comment by jparklev** [comment]
@levity it should have been separated in two really, a few of the tweaks I needed to get all the cdp types to show up for me when connected to a testchain, others could have been committed to develop first. Though they all arose for me in the context of this PR

**Comment by levity** [comment]
> I was able to get it up and running, but I had to make some adjustments to handle added contracts with no network properties.

Fixed in the last commit! Lemme know if there's anything else to do here before merging

**Comment by jparklev** [comment]
@levity I think we might hit a little snag with the kovan deployment, where b/c `pip` refers to the oracle security module, the current `getPrice` returns an odd value for the gem/usd feed price, which makes the cdp creation flow wonky. We could drop a manual `getStorageAt` back in for now until [#101](https://github.com/makerdao/dai.js/pull/101) lands. How does that feel?

Otherwise LGTM :)

**Comment by levity** [comment]
@jparklev ok, i'll review makerdao/dai.js#101, then once that's merged, ship a new point release and then update the deps here

**Comment by levity** [comment]
@jparklev i've got to jump on a call now, so if all looks good, feel free to merge

**Pull request merged**
