### PR TITLE
now gh test

### PR DESCRIPTION
**Pull request by jparklev**

### CODE REVIEW

**Comment by jparklev** [comment]
huzzah! @adrianleb @levity @abylaw @michaelelliot

**Comment by adrianleb** [comment]
Ohhh this is awesome!

**Comment by abylaw** [comment]
🕺

**Comment by adrianleb** [comment]
Screenshot 2019-04-02 at 18 18 30
Turning the zeit gh bot on without this change merged into master/develop broke staging for a few minutes earlier today.

**Comment by jparklev** [comment]
ah he was deploying pushes to develop, then aliasing those to staging using the `now.json` in that branch. good catch, need to be careful with our new bot

**Pull request closed without merging**
