### PR TITLE
Portis wallet integration

### PR DESCRIPTION
**Pull request by pcatana**
Hi team
This is an integration I've made with the https://www.portis.io/ wallet. I've built the plugin and already is published on npm (https://www.npmjs.com/package/@makerdao/dai-plugin-portis )

I'd like to have this integration merged with the master branch and be published on oasis.app. 
In this branch I've added the Portis logos in the wallet dropdown for signing up and added the plugin in the maker object. 
If you have any questions please ask.

### CODE REVIEW

**Comment by Padraic-O-Mhuiris** [comment]
Cool, will have a look

**Comment by Padraic-O-Mhuiris** [comment]
image

Wasn't able log in. Would need to figure this out for deployments but I'd hold off on fixing that just yet as we are making some changes to how this app is deployed. 

I wasn't able to submit a transaction to create a proxy locally so something needs to be investigated there.

**Comment by pcatana** [comment]
It runs perfectly locally. 
Also, in the portis dashboard it's defined to work for oasis.app domain ( not sure if this has anything to do with it ). 
The plugin is made to work for mainnet only: https://github.com/makerdao/dai-plugin-portis/blob/master/src/index.js#L13
Can easily make it work for kovan too if nedded.

**Comment by Padraic-O-Mhuiris** [comment]
aah, I was experimenting on kovan so that may be why it wasn't working. Please apply that fix if you could

**Comment by pcatana** [comment]
I just allowed the staging link in portis. Now I got a cookie problem:

**Review by Padraic-O-Mhuiris — APPROVED** [review]

**Comment by Padraic-O-Mhuiris** [comment]
LGTM

**Pull request merged**
