### PR TITLE
CDP-298 Get event history from Vulcanize

### PR DESCRIPTION
**Pull request by levity**
Waiting on http://vdb0-testing.vulcanize.io:5000/graphiql to support the [getManagedCdp](https://github.com/makerdao/vulcan.spec/blob/master/cdp-manager.graphql#L23) query

### CODE REVIEW

**Comment by tyler17** [comment]
What is the getManagedCdp query needed for @levity?

**Comment by levity** [comment]
> What is the getManagedCdp query needed for @levity?

This would be the simplest way for us to get the Vulcanize data when viewing a single CDP. I guess it's not a hard blocker though since we could do a two-step process of looking up the `urn` for a CDP and then querying Vulcanize on that.

**Comment by levity** [comment]
@tyler17 btw, not to disrupt any other planning going on, but if this were something you wanted to pick back up, that would be great :)

**Comment by tyler17** [comment]
Yeah happy to pick this back up.  Definitely not disrupting as I'm currently trying to break down the work for CDP-298.

I see, yeah looking up the urn first is how I [implemented it initially] (https://github.com/makerdao/dai.js/blob/90cd031571c1ac91d2cd1085e1808c4a9ec0cbcc/packages/dai-plugin-mcd/src/ManagedCdp.js#L153)

**Comment by levity** [comment]
Ha, I forgot that existed 😅
Still some more work to do before we can be passing around ManagedCdp instances everywhere in the portal, so for now feel free to copy-paste that into the function in reducers/cdps

**Comment by tyler17** [comment]
Good to know.  So to make sure I understand, the addition of GetManagedCdp would mean that rather than querying urnFrobs and passing in the urn as an argument, we would be able to get the same data by passing in a user's address to a similar query instead? Also, an address can have more than 1 managed cdp I believe, so how would getManagedCdp work?

**Comment by levity** [comment]
> Good to know. So to make sure I understand, the addition of GetManagedCdp would mean that rather than querying urnFrobs and passing in the urn as an argument, we would be able to get the same data by passing in a user's address to a similar query instead? Also, an address can have more than 1 managed cdp I believe, so how would getManagedCdp work?

Ah, sorry, I meant to link to the `getManagedCdp(id)` bit in the spec, not the one that takes `usr` as an argument. I agree the one using the user's address doesn't quite make sense. So we would take the CDP ID directly from the URL or from getCdpIds and pass that in.

**Comment by tyler17** [comment]
@levity The vdb deployment is running the 0.2.12 contracts, but the portal is up to 0.2.13 - so should we just merge this with the sdk call commented out and using mock data, and then switch to real data once the vdb contracts match up with the portal contracts? I got things hooked up locally with the 0.2.12 contracts

**Comment by levity** [comment]
> @levity The vdb deployment is running the 0.2.12 contracts, but the portal is up to 0.2.13 - so should we just merge this with the sdk call commented out and using mock data, and then switch to real data once the vdb contracts match up with the portal contracts? I got things hooked up locally with the 0.2.12 contracts

Sounds good to me

**Pull request merged**
