### PR TITLE
CDP-353 Rendering dropdown only when account is connected

### PR DESCRIPTION
**Pull request by sirromdev**

### CODE REVIEW

**Comment by sirromdev** [comment]
@abylaw I'm unsure if removing the dropdown is the right thing to do here? What do you think?

**Comment by abylaw** [comment]
@sirromdev What concerns do you have?

**Comment by sirromdev** [comment]
Well it's just that we're removing the dropdown altogether and it seems a bit bare. If a user happens to be in Read-only mode but was expecting to see the dropdown it may be helpful for them to have an indication on the navbar that they are in Read-only mode without hitting the hamburger menu.
Another thought is that we could move the connect button to where the dropdown while the user is in Read-only mode. Connecting your account would be a primary user-action and making that a 1-step over 2-step action (opening hamburger menu -> connecting account) would be more efficient.

**Comment by abylaw** [comment]
@sirromdev I see - that's fair! The solution you mentioned makes a lot of sense to me. It also seems to make sense for me to have a color indicator like we do for larger screens. I would approach a designer and ask for some quick feedback - both Micheal McKain and David Kim work on the MCD designs.

**Comment by sirromdev** [comment]
Having talked to David, he also agrees. I've added the connect button to the navbar and removed it from the hamburger dropdown. [gif](https://i.imgur.com/YMix6Ou.gifv)

**Comment by levity** [comment]
> Having talked to David, he also agrees. I've added the connect button to the navbar and removed it from the hamburger dropdown. [gif](https://i.imgur.com/YMix6Ou.gifv)

Nice, that looks great

**Pull request merged**
